# Generated by Django 2.1.5 on 2020-08-30 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=30)),
                ('location', models.TextField(max_length=800)),
                ('band_img', models.ImageField(default='places/None/no-img.jpg', upload_to='places/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='rockermind.MyUser')),
            ],
        ),
        migrations.CreateModel(
            name='Rocker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_name', models.CharField(max_length=30)),
                ('band_img', models.ImageField(default='band_members/None/no-img.jpg', upload_to='band_members/')),
                ('band_logo', models.ImageField(default='band_logo/None/no-img.jpg', upload_to='band_logo/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='rockermind.MyUser')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='rockermind.Role'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fan',
            name='tastes',
            field=models.ManyToManyField(blank=True, related_name='fans', to='rockermind.Genre'),
        ),
        migrations.AddField(
            model_name='fan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fans', to='rockermind.MyUser'),
        ),
    ]
