# Generated by Django 2.1.5 on 2020-08-30 17:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockermind', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rocker',
            name='members',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), default=list, size=None),
        ),
        migrations.AddField(
            model_name='rocker',
            name='songs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None),
        ),
    ]
