# Generated by Django 2.1.5 on 2020-08-30 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rockermind', '0002_auto_20200830_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rocker',
            name='members',
        ),
        migrations.RemoveField(
            model_name='rocker',
            name='songs',
        ),
    ]
