# Generated by Django 2.1.5 on 2020-08-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockermind', '0003_auto_20200830_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_song', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='rocker',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='bands', to='rockermind.BandMember'),
        ),
        migrations.AddField(
            model_name='rocker',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='band', to='rockermind.Song'),
        ),
    ]
