# Generated by Django 2.1.5 on 2020-08-30 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rockermind', '0005_rocker_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rocker',
            name='members',
        ),
        migrations.DeleteModel(
            name='BandMember',
        ),
    ]
