# Generated by Django 2.1.5 on 2020-08-30 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockermind', '0006_auto_20200830_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='rocker',
            name='biography',
            field=models.TextField(blank=True, max_length=1024),
        ),
    ]
