# Generated by Django 2.1.5 on 2020-08-30 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rockermind', '0007_rocker_biography'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='band_img',
            new_name='place_img',
        ),
    ]
