# Generated by Django 2.1.5 on 2020-08-31 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rockermind', '0008_auto_20200830_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rocker',
            name='songs',
        ),
        migrations.AddField(
            model_name='song',
            name='band',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='rockermind.Rocker'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='song',
            name='url_song',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
