# Generated by Django 2.1.5 on 2020-09-01 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rockermind', '0009_auto_20200831_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fan',
            name='tastes',
        ),
        migrations.AddField(
            model_name='fan',
            name='tastes',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fans', to='rockermind.Genre'),
            preserve_default=False,
        ),
    ]
