# Generated by Django 2.1.5 on 2020-09-01 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rockermind', '0010_auto_20200901_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rocker',
            name='genres',
        ),
        migrations.AddField(
            model_name='rocker',
            name='genres',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='band', to='rockermind.Genre'),
            preserve_default=False,
        ),
    ]
