# Generated by Django 2.1.5 on 2020-09-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockermind', '0011_auto_20200901_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='band',
        ),
        migrations.AddField(
            model_name='rocker',
            name='url_song_1',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='rocker',
            name='url_song_2',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='rocker',
            name='url_song_3',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
