# Generated by Django 2.1.5 on 2020-09-04 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rockermind', '0012_auto_20200901_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Band_by_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirmed', models.BooleanField()),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='rockermind.Rocker')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('cost', models.FloatField()),
                ('adult', models.BooleanField()),
                ('info', models.TextField(blank=True, max_length=1024)),
                ('is_confirmed', models.BooleanField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='rockermind.Owner')),
            ],
        ),
        migrations.AddField(
            model_name='band_by_event',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='rockermind.Event'),
        ),
    ]
