# Generated by Django 2.1.5 on 2020-09-09 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rockermind', '0014_auto_20200907_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('content', models.TextField(max_length=800)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='rockermind.MyUser')),
            ],
        ),
        migrations.AddField(
            model_name='fan',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='rockermind.Rocker'),
        ),
    ]
